//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YotsmogBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YotsmogBot.ConstantText", typeof(ConstantText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            [
        ///  &quot;在苏共二十三次代表大会上，列昂尼德同志作报告，他问：“我们这里有没有敌人？”\r\n一个人回答：“有一个，他坐在第四排第十八号位子上。”\r\n“为什么他是敌人？”\r\n“因为列宁说过‘敌人是不会打瞌睡的’，而我发现全场只有他一个人没有打瞌睡！”　&quot;,
        ///  &quot;一个莫斯科市民的鹦鹉丢了。这是只会骂人的鹦鹉，要是落到克格勃的手里可糟了。这人便在报纸上发表了一篇声明：“本人遗失鹦鹉一只。另，本人不同意它的政治观点。”&quot;,
        ///  &quot;列宁的夫人克鲁普斯卡娅曾经当面指出斯大林的专制独裁统治，令后者气急败坏，斯大林说：“你再说，我就宣布你不是列宁的妻子！”&quot;,
        ///  &quot;一个老师愁眉苦脸，贝利亚同志关切的询问：“怎么啦？我能帮您什么忙？”\r\n老师说：“拉甫连季同志，您帮不上忙，您看，现在的孩子都怎么啦：今天我问柳芭‘列夫·托尔斯泰是怎么死的？’她却说‘不是我干的。’我问萨沙，他也说‘不是我干的。’我问尼古拉，回答也一样！”\r\n第二天，贝利亚同志找到老师：“您可以放心了，他们已经招认他们杀了列夫·托尔斯泰。”&quot;,
        ///  &quot;列昂尼德同志去新德里拜访英迪拉先生，发现阿三随地小便， [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SovietJoke {
            get {
                return ResourceManager.GetString("SovietJoke", resourceCulture);
            }
        }
    }
}
